# cell types
EMPTY = 0
UP_WALL = 1
RIGHT_WALL = 2
DOWN_WALL = 3
LEFT_WALL = 4
FLOOR = 5
TOP_LEFT_CORNER = 6
TOP_RIGHT_CORNER = 7
BOTTOM_LEFT_CORNER = 8
BOTTOM_RIGHT_CORNER = 9

# directions
NORTH = 0
EAST = 1
SOUTH = 2
WEST = 3

# possible cells for each type of cell in North, East, South, West
Rules = {
    TOP_LEFT_CORNER: [EMPTY, UP_WALL, LEFT_WALL, EMPTY],
    TOP_RIGHT_CORNER: [EMPTY, EMPTY, RIGHT_WALL, UP_WALL],
    BOTTOM_LEFT_CORNER: [LEFT_WALL, DOWN_WALL, EMPTY, EMPTY],
    BOTTOM_RIGHT_CORNER: [RIGHT_WALL, EMPTY, EMPTY, DOWN_WALL],
    UP_WALL: [EMPTY, UP_WALL, FLOOR, UP_WALL],
    RIGHT_WALL: [RIGHT_WALL, EMPTY, RIGHT_WALL, FLOOR],
    DOWN_WALL: [FLOOR, DOWN_WALL, EMPTY, DOWN_WALL],
    LEFT_WALL: [LEFT_WALL, FLOOR, LEFT_WALL, EMPTY],
    FLOOR: [FLOOR, FLOOR, FLOOR, FLOOR]
}